/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * A source actor catalog with the timestamp it was mostly recently updated
 */
export class ActorCatalogWithUpdatedAt extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "catalog" })
  catalog?: Record<string, any>;

  @SpeakeasyMetadata()
  @Expose({ name: "updatedAt" })
  updatedAt?: number;
}
