/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class ActorCatalogWithUpdatedAtCatalog extends SpeakeasyBase {}

/**
 * A source actor catalog with the timestamp it was mostly recently updated
 */
export class ActorCatalogWithUpdatedAt extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "catalog" })
    @Type(() => ActorCatalogWithUpdatedAtCatalog)
    catalog?: ActorCatalogWithUpdatedAtCatalog;

    @SpeakeasyMetadata()
    @Expose({ name: "updatedAt" })
    updatedAt?: number;
}
