/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AirbyteStreamAndConfiguration } from "./airbytestreamandconfiguration";
import { Expose, Type } from "class-transformer";

/**
 * describes the available schema (catalog).
 */
export class AirbyteCatalog extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: AirbyteStreamAndConfiguration })
  @Expose({ name: "streams" })
  @Type(() => AirbyteStreamAndConfiguration)
  streams: AirbyteStreamAndConfiguration[];
}
