/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Categorizes well known errors into types for programmatic handling. If not set, the type of error is not well known.
 */
export enum AttemptFailureTypeEnum {
  ConfigError = "config_error",
  SystemError = "system_error",
  ManualCancellation = "manual_cancellation",
  RefreshSchema = "refresh_schema",
}
