/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class AttemptStats extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "bytesEmitted" })
  bytesEmitted?: number;

  @SpeakeasyMetadata()
  @Expose({ name: "estimatedBytes" })
  estimatedBytes?: number;

  @SpeakeasyMetadata()
  @Expose({ name: "estimatedRecords" })
  estimatedRecords?: number;

  @SpeakeasyMetadata()
  @Expose({ name: "recordsCommitted" })
  recordsCommitted?: number;

  @SpeakeasyMetadata()
  @Expose({ name: "recordsEmitted" })
  recordsEmitted?: number;

  @SpeakeasyMetadata()
  @Expose({ name: "stateMessagesEmitted" })
  stateMessagesEmitted?: number;
}
