/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { StreamTransform } from "./streamtransform";
import { Expose, Type } from "class-transformer";

/**
 * Describes the difference between two Airbyte catalogs.
 */
export class CatalogDiff extends SpeakeasyBase {
  /**
   * list of stream transformations. order does not matter.
   */
  @SpeakeasyMetadata({ elemType: StreamTransform })
  @Expose({ name: "transforms" })
  @Type(() => StreamTransform)
  transforms: StreamTransform[];
}
