/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { SynchronousJobRead } from "./synchronousjobread";
import { Expose, Type } from "class-transformer";

export enum CheckConnectionReadStatusEnum {
  Succeeded = "succeeded",
  Failed = "failed",
}

/**
 * Successful operation
 */
export class CheckConnectionRead extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "jobInfo" })
  @Type(() => SynchronousJobRead)
  jobInfo: SynchronousJobRead;

  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "status" })
  status: CheckConnectionReadStatusEnum;
}
