/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * determine how the schedule data should be interpreted
 */
export enum ConnectionScheduleType {
  Manual = "manual",
  Basic = "basic",
  Cron = "cron",
}
