/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum ConnectionScheduleTimeUnit {
    Minutes = "minutes",
    Hours = "hours",
    Days = "days",
    Weeks = "weeks",
    Months = "months",
}

/**
 * if null, then no schedule is set.
 */
export class ConnectionSchedule extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "timeUnit" })
    timeUnit: ConnectionScheduleTimeUnit;

    @SpeakeasyMetadata()
    @Expose({ name: "units" })
    units: number;
}
