/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ConnectionState } from "./connectionstate";
import { Expose, Type } from "class-transformer";

export class ConnectionStateCreateOrUpdate extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "connectionId" })
  connectionId: string;

  /**
   * Contains the state for a connection. The stateType field identifies what type of state it is. Only the field corresponding to that type will be set, the rest will be null. If stateType=not_set, then none of the fields will be set.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "connectionState" })
  @Type(() => ConnectionState)
  connectionState: ConnectionState;
}
