/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Successful operation
 */
export enum ConnectionStateTypeEnum {
  Global = "global",
  Stream = "stream",
  Legacy = "legacy",
  NotSet = "not_set",
}
