/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ConnectionRead } from "./connectionread";
import { Expose, Type } from "class-transformer";

/**
 * Successful operation
 */
export class ConnectionReadList extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: ConnectionRead })
  @Expose({ name: "connections" })
  @Type(() => ConnectionRead)
  connections: ConnectionRead[];
}
