/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { SourceDefinitionCreate } from "./sourcedefinitioncreate";
import { Expose, Type } from "class-transformer";

export class CustomSourceDefinitionCreate extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "sourceDefinition" })
  @Type(() => SourceDefinitionCreate)
  sourceDefinition: SourceDefinitionCreate;

  @SpeakeasyMetadata()
  @Expose({ name: "workspaceId" })
  workspaceId: string;
}
