/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AdvancedAuth } from "./advancedauth";
import { DestinationAuthSpecification } from "./destinationauthspecification";
import { DestinationSyncModeEnum } from "./destinationsyncmodeenum";
import { SynchronousJobRead } from "./synchronousjobread";
import { Expose, Type } from "class-transformer";

/**
 * Successful operation
 */
export class DestinationDefinitionSpecificationRead extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "advancedAuth" })
  @Type(() => AdvancedAuth)
  advancedAuth?: AdvancedAuth;

  @SpeakeasyMetadata()
  @Expose({ name: "authSpecification" })
  @Type(() => DestinationAuthSpecification)
  authSpecification?: DestinationAuthSpecification;

  /**
   * The specification for what values are required to configure the destinationDefinition.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "connectionSpecification" })
  connectionSpecification?: any;

  @SpeakeasyMetadata()
  @Expose({ name: "destinationDefinitionId" })
  destinationDefinitionId: string;

  @SpeakeasyMetadata()
  @Expose({ name: "documentationUrl" })
  documentationUrl?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "jobInfo" })
  @Type(() => SynchronousJobRead)
  jobInfo: SynchronousJobRead;

  @SpeakeasyMetadata()
  @Expose({ name: "supportedDestinationSyncModes" })
  supportedDestinationSyncModes?: DestinationSyncModeEnum[];
}
