/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { DestinationDefinitionRead } from "./destinationdefinitionread";
import { Expose, Type } from "class-transformer";

/**
 * Successful operation
 */
export class DestinationDefinitionReadList extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: DestinationDefinitionRead })
  @Expose({ name: "destinationDefinitions" })
  @Type(() => DestinationDefinitionRead)
  destinationDefinitions: DestinationDefinitionRead[];
}
