/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { DestinationCloneConfiguration } from "./destinationcloneconfiguration";
import { Expose, Type } from "class-transformer";

/**
 * The values required to configure the destination. The schema for this should have an id of the existing destination along with the configuration you want to change in case.
 */
export class DestinationCloneRequestBody extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "destinationCloneId" })
  destinationCloneId: string;

  @SpeakeasyMetadata()
  @Expose({ name: "destinationConfiguration" })
  @Type(() => DestinationCloneConfiguration)
  destinationConfiguration?: DestinationCloneConfiguration;
}
