/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum DestinationSyncMode {
    Append = "append",
    Overwrite = "overwrite",
    AppendDedup = "append_dedup",
}
