/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { OAuth2Specification } from "./oauth2specification";
import { Expose, Type } from "class-transformer";

export enum DestinationAuthSpecificationAuthTypeEnum {
  Oauth20 = "oauth2.0",
}

export class DestinationAuthSpecification extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "auth_type" })
  authType?: DestinationAuthSpecificationAuthTypeEnum;

  /**
   * An object containing any metadata needed to describe this connector's Oauth flow
   */
  @SpeakeasyMetadata()
  @Expose({ name: "oauth2Specification" })
  @Type(() => OAuth2Specification)
  oauth2Specification?: OAuth2Specification;
}
