/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class DestinationDefinitionIdWithWorkspaceId extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "destinationDefinitionId" })
  destinationDefinitionId: string;

  @SpeakeasyMetadata()
  @Expose({ name: "workspaceId" })
  workspaceId: string;
}
