/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { DestinationRead } from "./destinationread";
import { Expose, Type } from "class-transformer";

/**
 * Successful operation
 */
export class DestinationReadList extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: DestinationRead })
  @Expose({ name: "destinations" })
  @Type(() => DestinationRead)
  destinations: DestinationRead[];
}
