/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Successful Operation
 */
export class DiscoverCatalogResult extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "catalogId" })
  catalogId: string;
}
