/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { FieldSchema } from "./fieldschema";
import { Expose, Type } from "class-transformer";

export class FieldSchemaUpdate extends SpeakeasyBase {
    /**
     * JSONSchema representation of the field
     */
    @SpeakeasyMetadata()
    @Expose({ name: "newSchema" })
    @Type(() => FieldSchema)
    newSchema: FieldSchema;

    /**
     * JSONSchema representation of the field
     */
    @SpeakeasyMetadata()
    @Expose({ name: "oldSchema" })
    @Type(() => FieldSchema)
    oldSchema: FieldSchema;
}
