/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { StateBlob } from "./stateblob";
import { StreamState } from "./streamstate";
import { Expose, Type } from "class-transformer";

export class GlobalState extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "shared_state" })
    @Type(() => StateBlob)
    sharedState?: StateBlob;

    @SpeakeasyMetadata({ elemType: StreamState })
    @Expose({ name: "streamStates" })
    @Type(() => StreamState)
    streamStates: StreamState[];
}
