/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AttemptInfoRead } from "./attemptinforead";
import { JobDebugRead } from "./jobdebugread";
import { WorkflowStateRead } from "./workflowstateread";
import { Expose, Type } from "class-transformer";

/**
 * Successful operation
 */
export class JobDebugInfoRead extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: AttemptInfoRead })
  @Expose({ name: "attempts" })
  @Type(() => AttemptInfoRead)
  attempts: AttemptInfoRead[];

  @SpeakeasyMetadata()
  @Expose({ name: "job" })
  @Type(() => JobDebugRead)
  job: JobDebugRead;

  @SpeakeasyMetadata()
  @Expose({ name: "workflowState" })
  @Type(() => WorkflowStateRead)
  workflowState?: WorkflowStateRead;
}
