/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { JobRead } from "./jobread";
import { Expose, Type } from "class-transformer";

/**
 * Successful operation
 */
export class JobInfoLightRead extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "job" })
  @Type(() => JobRead)
  job: JobRead;
}
