/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { JobConfigType } from "./jobconfigtype";
import { Pagination } from "./pagination";
import { Expose, Type } from "class-transformer";

export class JobListRequestBody extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "configId" })
  configId: string;

  @SpeakeasyMetadata()
  @Expose({ name: "configTypes" })
  configTypes: JobConfigType[];

  @SpeakeasyMetadata()
  @Expose({ name: "includingJobId" })
  includingJobId?: number;

  @SpeakeasyMetadata()
  @Expose({ name: "pagination" })
  @Type(() => Pagination)
  pagination?: Pagination;
}
