/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { JobWithAttemptsRead } from "./jobwithattemptsread";
import { Expose, Type } from "class-transformer";

/**
 * Successful operation
 */
export class JobReadList extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: JobWithAttemptsRead })
  @Expose({ name: "jobs" })
  @Type(() => JobWithAttemptsRead)
  jobs: JobWithAttemptsRead[];

  /**
   * the total count of jobs for the specified connection
   */
  @SpeakeasyMetadata()
  @Expose({ name: "totalJobCount" })
  totalJobCount: number;
}
