/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum JobStatusEnum {
  Pending = "pending",
  Running = "running",
  Incomplete = "incomplete",
  Failed = "failed",
  Succeeded = "succeeded",
  Cancelled = "cancelled",
}
