/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum JobStatus {
    Pending = "pending",
    Running = "running",
    Incomplete = "incomplete",
    Failed = "failed",
    Succeeded = "succeeded",
    Cancelled = "cancelled",
}
