/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { JobTypeEnum } from "./jobtypeenum";
import { ResourceRequirements } from "./resourcerequirements";
import { Expose, Type } from "class-transformer";

/**
 * sets resource requirements for a specific job type for an actor definition. these values override the default, if both are set.
 */
export class JobTypeResourceLimit extends SpeakeasyBase {
  /**
   * enum that describes the different types of jobs that the platform runs.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "jobType" })
  jobType: JobTypeEnum;

  /**
   * optional resource requirements to run workers (blank for unbounded allocations)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "resourceRequirements" })
  @Type(() => ResourceRequirements)
  resourceRequirements: ResourceRequirements;
}
