/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { LogTypeEnum } from "./logtypeenum";
import { Expose } from "class-transformer";

export class LogsRequestBody extends SpeakeasyBase {
  /**
   * type/source of logs produced
   */
  @SpeakeasyMetadata()
  @Expose({ name: "logType" })
  logType: LogTypeEnum;
}
