/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Method used for computing final namespace in destination
 */
export enum NamespaceDefinitionType {
  Source = "source",
  Destination = "destination",
  Customformat = "customformat",
}
