/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * describes a normalization config for destination definition
 */
export class NormalizationDestinationDefinitionConfig extends SpeakeasyBase {
  /**
   * a field indicating the type of integration dialect to use for normalization.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "normalizationIntegrationType" })
  normalizationIntegrationType?: string;

  /**
   * a field indicating the name of the repository to be used for normalization. If the value of the flag is NULL - normalization is not used.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "normalizationRepository" })
  normalizationRepository?: string;

  /**
   * a field indicating the tag of the docker repository to be used for normalization.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "normalizationTag" })
  normalizationTag?: string;

  /**
   * whether the destination definition supports normalization.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "supported" })
  supported: boolean;
}
