/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum NotificationReadStatusEnum {
  Succeeded = "succeeded",
  Failed = "failed",
}

/**
 * Successful operation
 */
export class NotificationRead extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "status" })
  status: NotificationReadStatusEnum;
}
