/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum OperatorNormalizationOptionEnum {
  Basic = "basic",
}

export class OperatorNormalization extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "option" })
  option?: OperatorNormalizationOptionEnum;
}
