/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PrivateDestinationDefinitionRead } from "./privatedestinationdefinitionread";
import { Expose, Type } from "class-transformer";

/**
 * Successful operation
 */
export class PrivateDestinationDefinitionReadList extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: PrivateDestinationDefinitionRead })
  @Expose({ name: "destinationDefinitions" })
  @Type(() => PrivateDestinationDefinitionRead)
  destinationDefinitions: PrivateDestinationDefinitionRead[];
}
