/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { SourceDefinitionRead } from "./sourcedefinitionread";
import { Expose, Type } from "class-transformer";

/**
 * Successful operation
 */
export class PrivateSourceDefinitionRead extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "granted" })
  granted: boolean;

  @SpeakeasyMetadata()
  @Expose({ name: "sourceDefinition" })
  @Type(() => SourceDefinitionRead)
  sourceDefinition: SourceDefinitionRead;
}
