/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PrivateSourceDefinitionRead } from "./privatesourcedefinitionread";
import { Expose, Type } from "class-transformer";

/**
 * Successful operation
 */
export class PrivateSourceDefinitionReadList extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: PrivateSourceDefinitionRead })
  @Expose({ name: "sourceDefinitions" })
  @Type(() => PrivateSourceDefinitionRead)
  sourceDefinitions: PrivateSourceDefinitionRead[];
}
