/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { DestinationDefinitionRead } from "./destinationdefinitionread";
import { Expose, Type } from "class-transformer";

/**
 * Successful operation
 */
export class PrivateDestinationDefinitionRead extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "destinationDefinition" })
  @Type(() => DestinationDefinitionRead)
  destinationDefinition: DestinationDefinitionRead;

  @SpeakeasyMetadata()
  @Expose({ name: "granted" })
  granted: boolean;
}
