/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum ReleaseStageEnum {
  Alpha = "alpha",
  Beta = "beta",
  GenerallyAvailable = "generally_available",
  Custom = "custom",
}
