/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Path to a field/column/property in a stream to be selected. For example, if the field to be selected is a database column called "foo", this will be ["foo"]. Use multiple path elements for nested schemas.
 */
export class SelectedFieldInfo extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "fieldPath" })
  fieldPath?: string[];
}
