/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class SetInstancewideDestinationOauthParamsRequestBody extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "destinationDefinitionId" })
  destinationDefinitionId: string;

  @SpeakeasyMetadata()
  @Expose({ name: "params" })
  params: Record<string, any>;
}
