/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class SourceCloneConfiguration extends SpeakeasyBase {
  /**
   * The values required to configure the source. The schema for this must match the schema return by source_definition_specifications/get for the source.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "connectionConfiguration" })
  connectionConfiguration?: any;

  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;
}
