/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { SourceDefinitionRead } from "./sourcedefinitionread";
import { Expose, Type } from "class-transformer";

/**
 * Successful operation
 */
export class SourceDefinitionReadList extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: SourceDefinitionRead })
  @Expose({ name: "sourceDefinitions" })
  @Type(() => SourceDefinitionRead)
  sourceDefinitions: SourceDefinitionRead[];
}
