/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { SourceRead } from "./sourceread";
import { Expose, Type } from "class-transformer";

/**
 * Successful operation
 */
export class SourceReadList extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: SourceRead })
  @Expose({ name: "sources" })
  @Type(() => SourceRead)
  sources: SourceRead[];
}
