/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { StreamDescriptor } from "./streamdescriptor";
import { Expose, Type } from "class-transformer";

export class StreamState extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "streamDescriptor" })
  @Type(() => StreamDescriptor)
  streamDescriptor: StreamDescriptor;

  @SpeakeasyMetadata()
  @Expose({ name: "streamState" })
  streamState?: Record<string, any>;
}
