/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

/**
 * Stream schema using Json Schema specs.
 */
export class StreamJsonSchema extends SpeakeasyBase {}
