/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { JobConfigTypeEnum } from "./jobconfigtypeenum";
import { LogRead } from "./logread";
import { Expose, Type } from "class-transformer";

export class SynchronousJobRead extends SpeakeasyBase {
  /**
   * only present if a config id was provided.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "configId" })
  configId?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "configType" })
  configType: JobConfigTypeEnum;

  @SpeakeasyMetadata()
  @Expose({ name: "connectorConfigurationUpdated" })
  connectorConfigurationUpdated?: boolean;

  @SpeakeasyMetadata()
  @Expose({ name: "createdAt" })
  createdAt: number;

  @SpeakeasyMetadata()
  @Expose({ name: "endedAt" })
  endedAt: number;

  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id: string;

  @SpeakeasyMetadata()
  @Expose({ name: "logs" })
  @Type(() => LogRead)
  logs?: LogRead;

  @SpeakeasyMetadata()
  @Expose({ name: "succeeded" })
  succeeded: boolean;
}
