/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { GeographyEnum } from "./geographyenum";
import { Expose } from "class-transformer";

/**
 * Successful operation
 */
export class WebBackendGeographiesListResult extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "geographies" })
  geographies: GeographyEnum[];
}
