/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { WebBackendConnectionListItem } from "./webbackendconnectionlistitem";
import { Expose, Type } from "class-transformer";

/**
 * Successful operation
 */
export class WebBackendConnectionReadList extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: WebBackendConnectionListItem })
  @Expose({ name: "connections" })
  @Type(() => WebBackendConnectionListItem)
  connections: WebBackendConnectionListItem[];
}
