/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { WorkspaceRead } from "./workspaceread";
import { Expose, Type } from "class-transformer";

/**
 * Successful operation
 */
export class WorkspaceReadList extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: WorkspaceRead })
  @Expose({ name: "workspaces" })
  @Type(() => WorkspaceRead)
  workspaces: WorkspaceRead[];
}
